// Daily Debates feed, generated by the footballfight-liveops-agent.
// Host the agent's output/ directory anywhere static (GitHub Pages, S3, R2)
// and point this at it. The app fetches `${FEED_BASE_URL}/debates_YYYY-MM-DD.json`.
export const FEED_BASE_URL =
  "https://rockpaperwhatever.com/dailydebates";

export const APP_STORE_URL =
  "https://apps.apple.com/app/futbolfight/id6739887696";

export function todaysFeedUrl(date = new Date()) {
  const iso = date.toISOString().slice(0, 10);
  return `${FEED_BASE_URL}/debates_${iso}.json`;
}
